### ISSUE TITLE
Option

### ISSUE THREAD

**Issue by rkmiller131** [MosaicWebworks/FEC#38]
Even though this is a public base url and you're not breaking any security rules by having it in here, you could instead put the url in your .env to clean up the appearance of your code. You could then expose the public, base url in your example.env so that others can still know which external API you're using

https://github.com/MosaicWebworks/FEC/blob/faa2e651385cb8a52820736467649f10123d087d/server/routes.js#L7

**Comment by luckynumberthirteen** [comment]
Done
