### ISSUE TITLE
MVC Formatting

### ISSUE THREAD

**Issue by rkmiller131** [MosaicWebworks/FEC#39]
I like the idea of using routes from your index.js, but take it a step further in this file by separating out your controllers too.
Establish routes for each widget, such as:

// products
router.get('/products', productControllers.getProductByID); < -(or something)
router.get('/products/:product_id/styles', controllers.getProductStyles);
etc....

// reviews
router.get('/reviews', reviewControllers.getReviews) etc.

and then you could organize each widget's controller in it's own folder

OR

super separated (don't feel like you have to do it this way for FEC, but good to know about this alternative, as it's more common for large projects)

have your routes go to another routes folder (so in your index.js instead of app.use('/data', routes) you would require the folder
const routes = require(./routes)
and then set it up with routes(app), which by default will go to its own index.js:

const products = require('./products')
const reviews = require('./reviews') <-files in this routes folder

module.exports = (app) => {
        products(app)
        reviews(app)
        etc.
}

then in products.js, for example:
require the products controller
const products = require('../controllers/products)

module.exports = (app) => {
        app.get('/products', products.getAll)
        app.get('products/:product_id, products.getProductById)
        etc.
}

THEN (wow this really is a lot)
in your controllers for products, something like:

module.exports = {
        getAll: (req, res) => {}
        getProductByID: (req, res) => {}
}

https://github.com/MosaicWebworks/FEC/blob/faa2e651385cb8a52820736467649f10123d087d/server/routes.js#L5

**Comment by luckynumberthirteen** [comment]
done
