### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by rkmiller131** [MosaicWebworks/FEC#42]
I see you're using both event and e in the same line - maybe just pick one? you don't necessarily have to pass e as a parameter, the listenerEvent will have access to either e or event

https://github.com/MosaicWebworks/FEC/blob/faa2e651385cb8a52820736467649f10123d087d/client/src/components/Overview/ImageGallery.jsx#L22

**Comment by luckynumberthirteen** [comment]
Refactored to just use event, and not pass e as a parameter.  Thank you
