### ISSUE TITLE
Nothing wrong with this, but just some info

### ISSUE THREAD

**Issue by rkmiller131** [MosaicWebworks/FEC#45]
There are use cases for export vs export default. Typically if you only have one function/one component/one 'thing' in a file, export default is an easy way to access it outside of the module exports object (and you don't have to de-structure it). Export is handy though when you are exporting multiple 'things' and want to have access to them in a key:value format (which requires destructuring)

https://github.com/MosaicWebworks/FEC/blob/faa2e651385cb8a52820736467649f10123d087d/client/src/components/Overview/Overview.jsx#L52

**Comment by luckynumberthirteen** [comment]
done
