### ISSUE TITLE
Debugging/Refactor

### ISSUE THREAD

**Issue by rkmiller131** [MosaicWebworks/FEC#49]
So I noticed your drop down filter wasn't working, and there are a couple facets to this:

https://github.com/MosaicWebworks/FEC/blob/faa2e651385cb8a52820736467649f10123d087d/client/src/components/rr/ReviewList.jsx#L41-L79

In order for your state to change you'll need a new memory reference (line 46 and 49)
![Screenshot 2023-08-18 at 12 24 15 PM](https://github.com/MosaicWebworks/FEC/assets/21061780/0961deba-7493-4778-a236-691051929ed6)

You also need to make sure you are updating the list you intended:
![Screenshot 2023-08-18 at 12 26 06 PM](https://github.com/MosaicWebworks/FEC/assets/21061780/673c3e94-2868-426e-ae1b-4f94b6a2a6f6)

and 

![Screenshot 2023-08-18 at 12 26 35 PM](https://github.com/MosaicWebworks/FEC/assets/21061780/576dc4f4-f283-4bf0-9f6c-21b96c300ae0)

other notes, just preference:
Whenever you chain a lot of if/else like this, might be good for a switch statement

**Comment by Paula-Yang** [comment]
Refactored and fixed
